REGIONES_CHILE = (
    ('Arica y Parinacota', 'Arica y Parinacota'),
    ('Tarapacá', 'Tarapacá'),
    ('Antofagasta', 'Antofagasta'),
    ('Atacama', 'Atacama'),
    ('Coquimbo', 'Coquimbo'),
    ('Valparaíso', 'Valparaíso'),
    ('Metropolitana de Santiago', 'Metropolitana de Santiago'),
    ('Libertador General Bernardo O\'Higgins', 'Libertador General Bernardo O\'Higgins'),
    ('Maule', 'Maule'),
    ('Ñuble', 'Ñuble'),
    ('Biobío', 'Biobío'),
    ('La Araucanía', 'La Araucanía'),
    ('Los Ríos', 'Los Ríos'),
    ('Los Lagos', 'Los Lagos'),
    ('Aysén del General Carlos Ibáñez del Campo', 'Aysén del General Carlos Ibáñez del Campo'),
    ('Magallanes y de la Antártica Chilena', 'Magallanes y de la Antártica Chilena'),
)

CIUDADES_CHILE = {
    'Arica y Parinacota': (
        ('Arica', 'Arica'),
        ('Camarones', 'Camarones'),
        ('Putre', 'Putre'),
        ('General Lagos', 'General Lagos'),
    ),
    'Tarapacá': (
        ('Iquique', 'Iquique'),
        ('Alto Hospicio', 'Alto Hospicio'),
        ('Pozo Almonte', 'Pozo Almonte'),
        ('Camiña', 'Camiña'),
        ('Colchane', 'Colchane'),
        ('Huara', 'Huara'),
        ('Pica', 'Pica'),
    ),
    'Antofagasta': (
        ('Antofagasta', 'Antofagasta'),
        ('Mejillones', 'Mejillones'),
        ('Sierra Gorda', 'Sierra Gorda'),
        ('Taltal', 'Taltal'),
        ('Calama', 'Calama'),
        ('Ollagüe', 'Ollagüe'),
        ('San Pedro de Atacama', 'San Pedro de Atacama'),
        ('Tocopilla', 'Tocopilla'),
        ('María Elena', 'María Elena'),
    ),
    'Atacama': (
        ('Copiapó', 'Copiapó'),
        ('Caldera', 'Caldera'),
        ('Tierra Amarilla', 'Tierra Amarilla'),
        ('Chañaral', 'Chañaral'),
        ('Diego de Almagro', 'Diego de Almagro'),
    ),
    'Coquimbo': (
        ('La Serena', 'La Serena'),
        ('Coquimbo', 'Coquimbo'),
        ('Andacollo', 'Andacollo'),
        ('La Higuera', 'La Higuera'),
        ('Paihuano', 'Paihuano'),
        ('Vicuña', 'Vicuña'),
        ('Illapel', 'Illapel'),
        ('Canela', 'Canela'),
        ('Los Vilos', 'Los Vilos'),
        ('Salamanca', 'Salamanca'),
    ),
    'Valparaíso': (
        ('Valparaíso', 'Valparaíso'),
        ('Viña del Mar', 'Viña del Mar'),
        ('Concón', 'Concón'),
        ('Quintero', 'Quintero'),
        ('Puchuncaví', 'Puchuncaví'),
        ('Casablanca', 'Casablanca'),
        ('Juan Fernández', 'Juan Fernández'),
        ('San Antonio', 'San Antonio'),
        ('Algarrobo', 'Algarrobo'),
        ('Cartagena', 'Cartagena'),
        ('El Quisco', 'El Quisco'),
        ('El Tabo', 'El Tabo'),
        ('Santo Domingo', 'Santo Domingo'),
    ),
    'Metropolitana de Santiago': (
        ('Santiago', 'Santiago'),
        ('Cerrillos', 'Cerrillos'),
        ('Quilicura', 'Quilicura'),
        ('Recoleta', 'Recoleta'),
        ('Pudahuel', 'Pudahuel'),
        ('Lo Prado', 'Lo Prado'),
        ('Renca', 'Renca'),
        ('Conchalí', 'Conchalí'),
        ('Independencia', 'Independencia'),
        ('Providencia', 'Providencia'),
        ('Vitacura', 'Vitacura'),
        ('Las Condes', 'Las Condes'),
        ('La Reina', 'La Reina'),
        ('Ñuñoa', 'Ñuñoa'),
        ('Peñalolén', 'Peñalolén'),
        ('La Florida', 'La Florida'),
        ('La Granja', 'La Granja'),
        ('Macul', 'Macul'),
        ('San Joaquín', 'San Joaquín'),
        ('Pedro Aguirre Cerda', 'Pedro Aguirre Cerda'),
        ('San Miguel', 'San Miguel'),
        ('Lo Espejo', 'Lo Espejo'),
        ('La Cisterna', 'La Cisterna'),
        ('San Ramón', 'San Ramón'),
        ('El Bosque', 'El Bosque'),
        ('La Pintana', 'La Pintana'),
    ),
    'Libertador General Bernardo O\'Higgins': (
        ('Rancagua', 'Rancagua'),
        ('Codegua', 'Codegua'),
        ('Coinco', 'Coinco'),
        ('Coltauco', 'Coltauco'),
        ('Doñihue', 'Doñihue'),
        ('Graneros', 'Graneros'),
        ('Las Cabras', 'Las Cabras'),
        ('Machalí', 'Machalí'),
        ('Malloa', 'Malloa'),
        ('Mostazal', 'Mostazal'),
        ('Olivar', 'Olivar'),
        ('Peumo', 'Peumo'),
        ('Pichidegua', 'Pichidegua'),
        ('Quinta de Tilcoco', 'Quinta de Tilcoco'),
        ('Rengo', 'Rengo'),
        ('Requínoa', 'Requínoa'),
        ('San Vicente de Tagua Tagua', 'San Vicente de Tagua Tagua'),
    ),
    'Maule': (
        ('Talca', 'Talca'),
        ('Conservación', 'Conservación'),
        ('Constitución', 'Constitución'),
        ('Curepto', 'Curepto'),
        ('Empedrado', 'Empedrado'),
        ('Maule', 'Maule'),
        ('Pelarco', 'Pelarco'),
        ('Pencahue', 'Pencahue'),
        ('Río Claro', 'Río Claro'),
        ('San Clemente', 'San Clemente'),
        ('San Rafael', 'San Rafael'),
    ),
    'Ñuble': (
        ('Chillán', 'Chillán'),
        ('Bulnes', 'Bulnes'),
        ('Cobquecura', 'Cobquecura'),
        ('Coelemu', 'Coelemu'),
        ('Coihueco', 'Coihueco'),
        ('El Carmen', 'El Carmen'),
        ('Ninhue', 'Ninhue'),
        ('Ñiquén', 'Ñiquén'),
        ('Pemuco', 'Pemuco'),
        ('Pinto', 'Pinto'),
        ('Portezuelo', 'Portezuelo'),
        ('Quillón', 'Quillón'),
        ('Quirihue', 'Quirihue'),
        ('Ránquil', 'Ránquil'),
        ('San Carlos', 'San Carlos'),
        ('San Fabián', 'San Fabián'),
        ('San Ignacio', 'San Ignacio'),
        ('San Nicolás', 'San Nicolás'),
        ('Treguaco', 'Treguaco'),
        ('Yungay', 'Yungay'),
    ),
    'Biobío': (
        ('Concepción', 'Concepción'),
        ('Coronel', 'Coronel'),
        ('Chiguayante', 'Chiguayante'),
        ('Florida', 'Florida'),
        ('Hualpén', 'Hualpén'),
        ('Hualqui', 'Hualqui'),
        ('Lota', 'Lota'),
        ('Penco', 'Penco'),
        ('San Pedro de la Paz', 'San Pedro de la Paz'),
        ('Santa Juana', 'Santa Juana'),
        ('Talcahuano', 'Talcahuano'),
        ('Tomé', 'Tomé'),
    ),
    'La Araucanía': (
        ('Temuco', 'Temuco'),
        ('Carahue', 'Carahue'),
        ('Cunco', 'Cunco'),
        ('Curarrehue', 'Curarrehue'),
        ('Freire', 'Freire'),
        ('Galvarino', 'Galvarino'),
        ('Gorbea', 'Gorbea'),
        ('Lautaro', 'Lautaro'),
        ('Loncoche', 'Loncoche'),
        ('Melipeuco', 'Melipeuco'),
        ('Nueva Imperial', 'Nueva Imperial'),
        ('Padre las Casas', 'Padre las Casas'),
        ('Perquenco', 'Perquenco'),
        ('Pitrufquén', 'Pitrufquén'),
        ('Pucón', 'Pucón'),
        ('Saavedra', 'Saavedra'),
        ('Teodoro Schmidt', 'Teodoro Schmidt'),
        ('Toltén', 'Toltén'),
        ('Vilcún', 'Vilcún'),
        ('Villarrica', 'Villarrica'),
    ),
    'Los Ríos': (
        ('Valdivia', 'Valdivia'),
        ('Corral', 'Corral'),
        ('Lanco', 'Lanco'),
        ('Los Lagos', 'Los Lagos'),
        ('Máfil', 'Máfil'),
        ('Mariquina', 'Mariquina'),
        ('Paillaco', 'Paillaco'),
        ('Panguipulli', 'Panguipulli'),
    ),
    'Los Lagos': (
        ('Puerto Montt', 'Puerto Montt'),
        ('Calbuco', 'Calbuco'),
        ('Cochamó', 'Cochamó'),
        ('Fresia', 'Fresia'),
        ('Frutillar', 'Frutillar'),
        ('Los Muermos', 'Los Muermos'),
        ('Llanquihue', 'Llanquihue'),
        ('Maullín', 'Maullín'),
        ('Puerto Varas', 'Puerto Varas'),
        ('Castro', 'Castro'),
        ('Ancud', 'Ancud'),
        ('Chaitén', 'Chaitén'),
        ('Futaleufú', 'Futaleufú'),
        ('Hualaihué', 'Hualaihué'),
        ('Palena', 'Palena'),
    ),
    'Aysén del General Carlos Ibáñez del Campo': (
        ('Coyhaique', 'Coyhaique'),
        ('Lago Verde', 'Lago Verde'),
        ('Aysén', 'Aysén'),
        ('Cisnes', 'Cisnes'),
        ('Guaitecas', 'Guaitecas'),
        ('Chile Chico', 'Chile Chico'),
        ('Río Ibáñez', 'Río Ibáñez'),
    ),
    'Magallanes y de la Antártica Chilena': (
        ('Punta Arenas', 'Punta Arenas'),
        ('Laguna Blanca', 'Laguna Blanca'),
        ('Río Verde', 'Río Verde'),
        ('San Gregorio', 'San Gregorio'),
        ('Cabo de Hornos (Ex-Navarino)', 'Cabo de Hornos (Ex-Navarino)'),
        ('Antártica', 'Antártica'),
        ('Porvenir', 'Porvenir'),
        ('Primavera', 'Primavera'),
        ('Timaukel', 'Timaukel'),
        ('Natales', 'Natales'),
        ('Torres del Paine', 'Torres del Paine'),
    ),
}
