# Generated by Django 5.0.6 on 2024-07-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_pedido_fecha_pedido_alter_pedido_cantidad_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DireccionEnvio',
        ),
    ]
