# Generated by Django 5.0.6 on 2024-07-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_alter_pedido_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario_eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
