# Generated by Django 5.0.6 on 2024-07-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_pedido_usuario_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En_camino', 'En camino'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
