# Generated by Django 5.0.6 on 2024-07-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_alter_pedido_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='disco',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tarjeta_caducidad',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tarjeta_cvv',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tarjeta_numero',
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('tarjeta_numero', models.CharField(max_length=16)),
                ('tarjeta_caducidad', models.CharField(max_length=5)),
                ('tarjeta_cvv', models.CharField(max_length=4)),
                ('disco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.disco')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='aplicacion.pedido')),
            ],
        ),
    ]
