# Generated by Django 5.0.6 on 2024-07-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_remove_pedido_cantidad_remove_pedido_disco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario_eliminado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_usuario',
            field=models.CharField(default='npc', max_length=150),
            preserve_default=False,
        ),
    ]
